sudo: false

services:
  - mongodb

language: php

php:
  - 5.6

env:
  - TEST_DUMP=1

install:
  - phpenv config-add phpconfig.ini
  - composer install

addons:
  apt:
    sources:
      - mongodb-3.0-precise
    packages:
      - mongodb-org-server
      - mongodb-org-shell

before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.addUser("travis", "test");'

script:
  - vendor/bin/phpunit --exclude-group long && travis_wait 120 vendor/bin/phpunit --group long
