services:
  php:
    image: recruiterphp/recruiter-php
    build:
      context: .
      args:
        - PHP_VERSION=${PHP_VERSION}
      tags:
        - latest
    working_dir: /app
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
      - MONGODB_URI=mongodb://mongodb:27017/recruiter
    depends_on:
      - mongodb

  mongodb:
    image: mongo:8
    container_name: recruiter_mongodb
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
